name = "SIR_model"
uuid = "57cc29ec-7704-476b-9bc9-db5658df7098"
authors = ["Hazzoz <hwils2019@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
